INSERT INTO items (name, code, description, unit_price) VALUES ('Ginseng 15 Tablets', 'T001', 'Ginseng 15 Tablets', 2100.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Active Liver 30 Tablets', 'T002', 'Active Liver 30 Tablets', 1500.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Echinacea Root Tea 10 Sachets', 'B001', 'Echinacea Root Tea 10 Sachets', 1650.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Ginkgo Fruits 70g', 'F001', 'Ginkgo Fruits 70g', 2400.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Elderberry 20 Lozenges', 'T003', 'Elderberry 20 Lozenges', 3210.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Baraca Green Tea 40 Sachets', 'B002', 'Baraca Green Tea 40 Sachets', 1650.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Turmeric 18 Capsules', 'T004', 'Turmeric 18 Capsules', 2150.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Ginseng 25 Tablets', 'T005', 'Ginseng 25 Tablets', 3800.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Kothalahimbutu Biscuits 100g', 'S001', 'Kothalahimbutu Biscuits 100g', 950.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Migraine Relief 18 Tablets', 'T006', 'Migraine Relief 18 Tablets', 3000.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Echinacea Root Tea 20 Sachets', 'B003', 'Echinacea Root Tea 20 Sachets', 2600.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Ginkgo Fruits 140g', 'F002', 'Ginkgo Fruits 140g', 4500.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Valerian Tea 20 Sachets', 'B004', 'Valerian Tea 20 Sachets', 3700.00);
INSERT INTO items (name, code, description, unit_price) VALUES ('Milk Thistle 18 Capsules', 'T007', 'Milk Thistle 18 Capsules', 3400.00);